name: Lint Python Code

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas apache-airflow flake8

      - name: Set PYTHONPATH for local modules
        run: |
          echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Create Flake8 config
        run: |
          echo "[flake8]" > .flake8
          echo "max-line-length = 0" >> .flake8
          echo "exclude = .git,__pycache__,docs" >> .flake8

      - name: Run Flake8
        run: |
          flake8 . --count --show-source --statistics
